version: '2'
services:
    music-app:
        image: music
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://music-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=music
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    music-mongodb:
        extends:
            file: mongodb.yml
            service: music-mongodb
